default:
  close:
    comment: ⚠️ This has been marked to be closed in $DELAY.
    delay: 7d

labels:
  wontfix: close
  invalid: close
  duplicate:
    action: close
    delay: 1d
    comment: This issue has been marked as a duplicate. Closing in $DELAY . . .
  stale:
    action: close
    comment: false
  "squash when passing": merge
  "rebase when passing": merge
  "merge when passing": merge
  reminder:
    action: comment
    delay: 1d
    message: You asked to remind you about this $DELAY ago

merges:
  - action: delete_branch

comments:
  - action: label
    pattern: /duplicate of/i
    labels:
      - duplicate
  - action: label
    pattern: /remind/i
    labels:
      - reminder
  - action: delete_comment
    pattern: /remind/i

commits:
  - action: label
    pattern: /merge when passing/i
    labels:
      - merge when passing
  - action: label
    pattern: /squash when passing/i
    labels:
      - squash when passing
  - action: label
    pattern: /rebase when passing/i
    labels:
      - rebase when passing

# TODO conventional change log
